pipeline {
    agent {
        kubernetes {
            defaultContainer 'jnlp'
            yaml """
kind: Pod
metadata:
  name: worker
spec:
  containers:
  - name: worker
    image: bharathpantala/jenkins_agent:latest
    imagePullPolicy: "IfNotPresent"
    command:
    - cat
    tty: true
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
  restartPolicy: Never
  volumes:
      - name: dockersock
        hostPath:
          path: "/var/run/docker.sock"
"""
        }
    }
    environment {
        AWS_ACCOUNT_ID="587219698707"
        AWS_DEFAULT_REGION="us-east-1" 
        IMAGE_REPO_NAME="jenkins_agent"
        IMAGE_TAG="v2021.9"
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
        AWS_CREDS_ID = "jenkins-cli-secrets"
    }
   
    stages {
        // Building Docker images
        stage('Building Image') {
            steps{
                script {
                sh "docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} ./jenkins/workers"
                }
            }
        }
    }
}
