persistence:
  enabled: true
  existingClaim: sonarqube-pvc

ingress:
  enabled: true
  hosts:
    - name: sonarqube.intranet.securonix.net
      path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "2048m"